#!/usr/bin/env sh

set -e

DB_PATH="$(mktemp).db"
SERVER_PORT=3000
export DB_PATH
export SERVER_PORT

base_url="http://localhost:$SERVER_PORT"
cookie_jar="$(mktemp).cookie"
last_result=''

die() {
	printf '\e[31m%b\e[0m' "$1"
	kill -9 "$PID"
	exit 1
}

runtest() {
	method="$1"
	url="$2"
	pattern="$3"
	payload="$4"
	actual="$(curl -c "$cookie_jar" -b "$cookie_jar" -s -X "$method" "$base_url$url" -d "$payload")"
	echo "$actual" | grep -q "$pattern" || die "Expected \n\t- '$actual' \nto match \n\t- '$pattern' \n@ $method: $url"
	last_result="$actual"
}

make
echo "Using database $DB_PATH"
echo "Using cookie jar $cookie_jar"
node dist/server.js &
PID="$!"

until curl "$base_url" 1>/dev/null 2>/dev/null; do
	sleep 1
done

runtest 'POST' '/api/account' '{"id":".*","email":"testuser@domain.org"}' '{"email":"testuser@domain.org","password":"password"}'
runtest 'POST' '/api/account/login' '{"authenticated":true}' '{"email":"testuser@domain.org","password":"password"}'
runtest 'POST' '/api/account/login' '{"authenticated":false}' '{"email":"testuser@domain.org","password":"none"}'

runtest 'GET' '/api/todo/' '\[\]' ''
runtest 'POST' '/api/todo/' '{"id":".*","title":"My title","description":"My Description","state":0}' '{"title": "My title", "description": "My Description", "state": 0}'
lastid=$(echo "$last_result" | jq --raw-output '.id')
runtest 'GET' '/api/todo/' "\[{\"id\":\"$lastid\",\"title\":\"My title\",\"description\":\"My Description\",\"state\":0}\]" ''
runtest 'PUT' "/api/todo/$lastid" '{"id":".*","title":"My title","description":"My Description 2","state":0}' '{"title": "My title", "description": "My Description 2", "state": 0}'
runtest 'GET' '/api/todo/' "\[{\"id\":\"$lastid\",\"title\":\"My title\",\"description\":\"My Description 2\",\"state\":0}\]" ''
runtest 'DELETE' "/api/todo/$lastid" '' ''
runtest 'GET' '/api/todo/' '\[\]' ''

echo 'Tests completed successfully'
kill -9 "$PID"
